# coding: utf-8

"""
    Asterisk-LA API

    Asterisk LA connector internal  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import liveagent_calls_internal_api
from liveagent_calls_internal_api.models.call import Call  # noqa: E501
from liveagent_calls_internal_api.rest import ApiException


class TestCall(unittest.TestCase):
    """Call unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCall(self):
        """Test Call"""
        # FIXME: construct object with mandatory attributes with example values
        # model = liveagent_calls_internal_api.models.call.Call()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
