# coding: utf-8

"""
    Asterisk-LA API

    Asterisk LA connector internal  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import liveagent_calls_internal_api
from liveagent_calls_internal_api.api.calls_internal_api import CallsInternalApi  # noqa: E501
from liveagent_calls_internal_api.rest import ApiException


class TestCallsInternalApi(unittest.TestCase):
    """CallsInternalApi unit test stubs"""

    def setUp(self):
        self.api = liveagent_calls_internal_api.api.calls_internal_api.CallsInternalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_call_cancel_create(self):
        """Test case for call_cancel_create

        Cancel outgoing call (before the agent initiated it on external device)  # noqa: E501
        """
        pass

    def test_call_create(self):
        """Test case for call_create

        Originate new call  # noqa: E501
        """
        pass

    def test_call_listen(self):
        """Test case for call_listen

        Request call listening  # noqa: E501
        """
        pass

    def test_call_redirect(self):
        """Test case for call_redirect

        Redirect call (Complete attended transfer)  # noqa: E501
        """
        pass

    def test_call_redirect_refer(self):
        """Test case for call_redirect_refer

        Redirect call by refer (Complete attended transfer)  # noqa: E501
        """
        pass

    def test_call_status(self):
        """Test case for call_status

        Return the status of call  # noqa: E501
        """
        pass

    def test_call_stop_listen(self):
        """Test case for call_stop_listen

        Stop call listening  # noqa: E501
        """
        pass

    def test_call_transfer(self):
        """Test case for call_transfer

        Blind transfer call to a different number  # noqa: E501
        """
        pass

    def test_dtmf_channel(self):
        """Test case for dtmf_channel

        Send provided DTMF to channel  # noqa: E501
        """
        pass

    def test_end_channel(self):
        """Test case for end_channel

        End channel  # noqa: E501
        """
        pass

    def test_get_recording(self):
        """Test case for get_recording

        Download a call recording file  # noqa: E501
        """
        pass

    def test_hold_channel(self):
        """Test case for hold_channel

        Hold channel  # noqa: E501
        """
        pass

    def test_mute_channel(self):
        """Test case for mute_channel

        Mute channel  # noqa: E501
        """
        pass

    def test_unhold_channel(self):
        """Test case for unhold_channel

        Unhold channel  # noqa: E501
        """
        pass

    def test_unmute_channel(self):
        """Test case for unmute_channel

        Unmute channel  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
