# coding: utf-8

"""
    Asterisk-LA API

    Asterisk LA connector internal  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import liveagent_calls_internal_api
from liveagent_calls_internal_api.api.resources_api import ResourcesApi  # noqa: E501
from liveagent_calls_internal_api.rest import ApiException


class TestResourcesApi(unittest.TestCase):
    """ResourcesApi unit test stubs"""

    def setUp(self):
        self.api = liveagent_calls_internal_api.api.resources_api.ResourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_resources(self):
        """Test case for resources

        List alive objects and threads  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
