# coding: utf-8

"""
    Asterisk-LA API

    Asterisk LA connector internal  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import liveagent_calls_internal_api
from liveagent_calls_internal_api.api.sounds_api import SoundsApi  # noqa: E501
from liveagent_calls_internal_api.rest import ApiException


class TestSoundsApi(unittest.TestCase):
    """SoundsApi unit test stubs"""

    def setUp(self):
        self.api = liveagent_calls_internal_api.api.sounds_api.SoundsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sound_add(self):
        """Test case for sound_add

        Uploads new sound. This is used mainly for checking if sound has correct format. Sounds used in IVR are lazy converted when needed.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
