# coding: utf-8

# flake8: noqa
"""
    Asterisk-LA API

    Asterisk LA connector internal  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from liveagent_calls_internal_api.models.call import Call
from liveagent_calls_internal_api.models.error_response import ErrorResponse
from liveagent_calls_internal_api.models.ok_response import OkResponse
